apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cert-manager-webhook-domeneshop.fullname" . }}
  labels:
    app: {{ include "cert-manager-webhook-domeneshop.name" . }}
    chart: {{ include "cert-manager-webhook-domeneshop.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
# Grant the webhook permission to read the ConfigMap containing the Kubernetes
# apiserver's requestheader-ca-certificate.
# This ConfigMap is automatically created by the Kubernetes apiserver.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cert-manager-webhook-domeneshop.fullname" . }}:webhook-authentication-reader
  namespace: kube-system
  labels:
    app: {{ include "cert-manager-webhook-domeneshop.name" . }}
    chart: {{ include "cert-manager-webhook-domeneshop.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "cert-manager-webhook-domeneshop.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
# apiserver gets the auth-delegator role to delegate auth decisions to
# the core apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cert-manager-webhook-domeneshop.fullname" . }}:auth-delegator
  labels:
    app: {{ include "cert-manager-webhook-domeneshop.name" . }}
    chart: {{ include "cert-manager-webhook-domeneshop.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "cert-manager-webhook-domeneshop.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
# Grant cert-manager permission to validate using our apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cert-manager-webhook-domeneshop.fullname" . }}:domain-solver
  labels:
    app: {{ include "cert-manager-webhook-domeneshop.name" . }}
    chart: {{ include "cert-manager-webhook-domeneshop.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - {{ .Values.groupName }}
    resources:
      - '*'
    verbs:
      - 'create'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cert-manager-webhook-domeneshop.fullname" . }}:domain-solver
  labels:
    app: {{ include "cert-manager-webhook-domeneshop.name" . }}
    chart: {{ include "cert-manager-webhook-domeneshop.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cert-manager-webhook-domeneshop.fullname" . }}:domain-solver
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ .Values.certManager.serviceAccountName }}
    namespace: {{ .Values.certManager.namespace }}
# Grant the webhook permission to read secrets in the release namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "cert-manager-webhook-domeneshop.fullname" . }}:secret-reader
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "cert-manager-webhook-domeneshop.name" . }}
    chart: {{ include "cert-manager-webhook-domeneshop.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cert-manager-webhook-domeneshop.fullname" . }}:secret-reader
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "cert-manager-webhook-domeneshop.name" . }}
    chart: {{ include "cert-manager-webhook-domeneshop.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cert-manager-webhook-domeneshop.fullname" . }}:secret-reader
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: {{ include "cert-manager-webhook-domeneshop.fullname" . }}
  namespace: {{ .Release.Namespace }}
# Grant the webhook permission to read secrets in the cert-manager namespace.
# This is required and must be uncommented if you are using a ClusterIssuer
# instead of a Issuer, and you have not changed the cluster resource location
# for cert-manager.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "cert-manager-webhook-domeneshop.fullname" . }}:secret-reader
  namespace: {{ .Values.certManager.namespace }}
  labels:
    app: {{ include "cert-manager-webhook-domeneshop.name" . }}
    chart: {{ include "cert-manager-webhook-domeneshop.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cert-manager-webhook-domeneshop.fullname" . }}:secret-reader
  namespace: {{ .Values.certManager.namespace }}
  labels:
    app: {{ include "cert-manager-webhook-domeneshop.name" . }}
    chart: {{ include "cert-manager-webhook-domeneshop.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cert-manager-webhook-domeneshop.fullname" . }}:secret-reader
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: {{ include "cert-manager-webhook-domeneshop.fullname" . }}
  namespace: {{ .Release.Namespace }}
